insert into Groups values(01, 'TECHNICAL LITERATURE');
insert into Groups values(11, 'ENGINE');
insert into Groups values(12, 'ENGINE ELECTRICAL SYSTEM');
insert into Groups values(13, 'FUEL PREPARATION SYSTEM');
insert into Groups values(16, 'FUEL SUPPLY');
insert into Groups values(17, 'RADIATOR');
insert into Groups values(18, 'EXHAUST SYSTEM');
insert into Groups values(21, 'CLUTCH');
insert into Groups values(22, 'ENGINE AND TRANSMISSION SUSPENSION');
insert into Groups values(23, 'MANUAL TRANSMISSION');
insert into Groups values(24, 'AUTOMATIC TRANSMISSION');
insert into Groups values(25, 'GEARSHIFT');
insert into Groups values(26, 'DRIVE SHAFT');
insert into Groups values(31, 'FRONT AXLE');
insert into Groups values(32, 'STEERING');
insert into Groups values(33, 'REAR AXLE');
insert into Groups values(34, 'BRAKES');
insert into Groups values(35, 'PEDALS');
insert into Groups values(36, 'WHEELS');
insert into Groups values(41, 'BODYWORK');
insert into Groups values(51, 'VEHICLE TRIM');
insert into Groups values(52, 'SEATS');
insert into Groups values(54, 'SLIDING ROOF / FOLDING TOP');
insert into Groups values(61, 'VEHICLE ELECTRICAL SYSTEM');
insert into Groups values(62, 'INSTRUMENTS, MEASURING SYSTEMS');
insert into Groups values(63, 'LIGHTING');
insert into Groups values(64, 'HEATER AND AIR CONDITIONING');
insert into Groups values(65, 'AUDIO, NAVIGATION, ELECTRONIC SYSTEMS');
insert into Groups values(66, 'DISTANCE SYSTEMS, CRUISE CONTROL');
insert into Groups values(71, 'EQUIPMENT PARTS');
insert into Groups values(72, 'RESTRAINT SYSTEM AND ACCESSORIES');
insert into Groups values(82, 'UNIVERSAL ACCESSORIES');
insert into Groups values(83, 'AUXILIARY MATERIALS, FLUIDS/COLORSYSTEM');
insert into Groups values(84, 'COMMUNICATION SYSTEMS');
insert into Groups values(85, 'COMPLETE WHEELS, TIRES AND WHEEL RIMS');
insert into Groups values(88, 'INSPECTION KITS');
